### ISSUE TITLE
Error installing 5.22.0_64_PDL

### ISSUE THREAD

**Issue by shawnlaffan** [dnmfarrell/berrybrew#10]
The URL and checksum look like they have been swapped in commit 8592178c383f5e1e411344f07313a2a12d9a532b

Regards,
Shawn.

```
C:\Users\shawn>berrybrew install 5.22.0_64_PDL
Downloading 9024ce63c2fe404e7488db827171a9262c5a4830 to C:\berrybrew\temp\strawberry-perl-5.22.0.1-64bit-PDL.zip

Unhandled Exception: System.Net.WebException: Could not find file 'C:\Users\shawn\9024ce63c2fe404e7488db827171a9262c5a4830'. ---> System.Net.WebException: Could not find file 'C:\Users\shawn\9024ce63c2fe404e7488db827171a9262c5a4830'. ---> System.IO.FileNotFoundException: Could not find file 'C:\Users\shawn\9024ce63c2fe404e7488db827171a9262c5a4830'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   --- End of inner exception stack trace ---
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   at System.Net.FileWebRequest.GetResponseCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Berrybrew.Berrybrew.Fetch(StrawberryPerl perl)
   at Berrybrew.Berrybrew.Main(String[] args)
```

**Comment by dnmfarrell** [comment]
Good catch, thanks!

**Comment by dnmfarrell** [comment]
Fixed
